// Manually add your messages here
const messages = [
  "Happy Happiest Birthday Richie! Idk what to even say. You just know it. I hope you have one of the best day and know how much you are loved. Keep being you and I love you  - Sunshine",
  "HAPPY BIRTHDAYY RICHIE <3 I love you so fucking much!! I don't think I can put it into words how much you mean to me. You are one of the most genuine people I met and I'm grateful to have you in my life. Thank you for making me feel safe when I'm with you. I know I have done a lot of shit but you never left me and instead you pulled me back. Just wanna say that I will always be there for you Richie, no matter what. I'm your kiddo, remember? Love you to the moon and back. Happy birthday once again!! Also ew you're old-Nithya",
  "Wish you a very very Happy Birthday Richieeeeee 🥹🥹🫶🫶 I'm so glad that I finally got to meet you at Loucid Dreams in Mumbai, you are just as amazing irl as you are online. I hope you have an amazing year ahead dude, we fucking saw Louis liveeee 😭😭❤‍🩹❤‍🩹 I hope we get to see the others live too some day, I'm sure we will!!Lots of love xxx- Sal ×͜×",
  "Happy Birthday bro 🥳🎉💝🎁🎊💐 God bless you and i would like to thank you to come in my life when I was damn alone. You tagging me and noticing me really meant way more than you realise. Thank you for always being there and i promise that I will be here too always by your side even if we have lots of distance between us. You the brother I always needed. - Prab",
  "Happy birthday bhaiiiiii Enjoy ur day🎂🎂 - Mayank ",
  "Happy Birthday Richie bhaiya!! You are one of the best people I met last year I am so grateful to call you bhaiya. You are really the best brother any one could have. Happy Birthday once again ✨ You are getting old 😂😂 - Devanshi ",
  "HELU BHAIYA 🤭 HAPPY HAPPY BIRTHDAY TO YOUUUUU HOPE YOU HAVE AN AMAZING DAY AHEAD I AM BERRY BERRY GRATEFUL FOR YOU AND YOUR COMPLIMENTS 😝 tumala mala marathi sikhane ki hai 😋 HAPPY BIRTHDAY 🥳  - Krisha ",
  "Happy birthday to one of the best people I know! May your day be as amazing as you are.  Age is just a number, but celebrations are timeless.  - Zenia",
  "Happiest Birthdayyyy RF 🍫✨ stay happy happy! Keep being you.. thank you for always trying and create a safe place for everyone✨🌻 Sendingggg lots of good wishesss.. have a pyaara sa din 🪄 and keep shininggg 🌟 ik things might seem hard sometimes but keep goinggg uh got thisss! We're so proud of uhh! ✨🍫🪄 - JP",
  "HAPPY BIRTHDAYYYYYYY!!!!! Thankyou for being the cool older brother I never had. You make me feel really safe and warm and I looooove hanging out with you. You're getting buddha but you'll always be the coolest. Love youuuuu ❤️ - Sreenidhi ",
  "Happy birthday Richie Rich 💜 I hope you have an amazing birthday 🌼 you're the kindest selfless person I've met who do soo much for others with no questions asked. I feel honoured to call you my friend really you mean a lot to me✨️ and really really hope that you will let people around you know the real you and let them take care of you like you do for them. Trust me you're not causing anyone inconvenience and no one's judging you soo please let us know.💜✨️ Lots of love and hugs 🫶🏻🫂  - Gun Gun ",
  "Hey Richie lalaaaaa!!!! Whishing you a birthday as joyful and beautiful as you have made me feel in times. İ know İ am not really active nowadays and that aap mujhse thora naraaz ho, but İ will always and forever be grateful to have known you and to be a part of the 1D group. May your day be filled with loads of joy and beautiful memories to cherish ( Agar drink kam karo ge to shayad wo memories yaad bhi reh jayen😭) And just a friendly reminder, aap mazeed burhe ho gaye ho 🙂🤟. Have a Good one!!!!Love ya✨💜💐 - Ifrah",
  "Happy Birthday Neighbour 😊 God bless you Have a great day. I know we don't talk much but I was fun drinking with you. Kindly send some beer bottles home - Caro",
  "Happiest birthday to da best concert buddy 🥳 - Chakshu",
  "I wish you the happiest birthday Richie bhai 🥳🤗.Thank you for creating a safe space for the people in the group when all of us were in a bad place and always ensuring that each and every one felt comfortable to vent out or share the littlest parts of our lives.When rest of the world judged us for being a part of the fandom this group helped us to embrace it and you played a major part in this.I wish there is nothing but success for you in the forthcoming years x - Prarthana",
  "Happy birthday Richie. Have the best year ahead. Looking forward to meeting u soon!! You're the bessstttt - Rai",
  "Hey Richie, Happy birthday🎂 have an amazing one! Hope all your wishes come true. - Ahishri",
  "happy birthday dude! A massive shoutout to you for helping in bringing all us directioners together. You're like our MVP fr. Really appreciate you man! (and i'm like totally jealous of your hair :) ) - Saveri",
  "Dear Richie bhaiya, Happy happy Birthday I hope you have an amazing one cuz you deserve it!!!! Thank you for creating such an incredible safe space for all of us!!,thank you for being so sweet and kind (stop calling me dumb plij hehe😭😭),sending lots of love and hugs to you💓💓🫂🫂✨️✨️. HAPPY BIRTHDAY YAYAYAYAYA🥳🥳🕺🏻🕺🏻✨️✨️🎀🎀  - Vaishnavi",
  "Hey Richieeeee! I just want to wish you a very happy birthday. I haven’t met you in person yet, but I’m sure you’re a wonderful person. You always try to bring happiness to those around you. I know you’re going through a lot, yet you never show it and always stand by your friends. I visit Mumbai often, and I hope we can meet someday. God bless you, and thank you for always looking out for us. - Raj",
  "Happy Birthday Richie Rich 🤑 Wishing you more boozes and hair growth this new year of life 😄 - Precilla ",
  "happy birthday richie! thanks for existing, I guess? thank you so much for finding our unreleased songs and making it available for us and also for asking me from time to time how I'm doing. It feels nice to be seen, yk. I hope you take care of yourself the way you care for others. have a prosperous year ahead. Lots of love ❤️ ❤️ ❤️ ❤️ ❤️  - Shrishti Roy ",
  "Happy Bday bro, keep shining and rockin 🫂- Bayle",
  "Happiest Birthday Mariner 🖤I feel this name suits you a lot more than Richard as this name symbolises inner power,strength, love, care you have for all you're family friends and everyone around you 🩵Be the same always ❤️ and never let your inner spark die and be always goofy, weird and cartoon that you are ☺️😊 - Kasturi",
  "Bhai, you know it all - the good, the bad, the happy, the sad, and the in between. You've been there in more ways than I can count, and we've managed to find our way back through ups and downs we didn't see coming. Your family, you always always will be and no matter what, I know I can count on you. This is my millionth reminder that I'm going to be here to, come what may, I know you know, but I needed to tell you anyway. Happy Birthday Bhai, I love you.  - Aafreen",
  "Richieeee!!! Happiest birthday to you!!! ❤️ I might not be very active, but I’m constantly grateful that you’ve created this group and a safe space for everyone, including me! Talking and getting to know you a little has been a joy too, and I’m so glad I know you!! I couldn’t coordinate and meet you at Lolla, but hopefully the next time I’m in Mumbai we can chill! Hope the end of 20s is the best time for you!!!! Sending you tons of love on your special day ❤️❤️ - Chahat",
  "Hope your day is filled with lots of love and happiness. Wishing you the happiest birthday Richie! Thank you for creating a safe space for everyone in the group. May you receive all the happiness in life! - Kaushikee",
  "hey, Richie.....Happy birthday.... - Dharshini Arun",
  "Wishing u a really happy birthday Richieeee🥹🫶🏻 Thank you for always being there for everyone! U have us all with you🫂 May u get everything u want and more❤️ - Stuti",
  "Happy Birthday Richie! I hope you have an amazing day and celebration surrounded by everyone who you love, and everyone who supports you and makes you happy. You do so much to make a safe space for all of us - thank you so much for all that you do. It means a lot to all of us, including me - and I hope that you have found a safe space too. I hope that your day is filled with the same love, support, and kindness that you give all of us and that you have an amazing year, filled with happiness and love, wherever it may take you. And don’t forget to stay away from water while you’re on the ship, or you may dissolve. Lots of love as always, Vaishali.",
  "happy birthday richie!! i hope you have an absolutely amazing year ahead <3 you're one of the kindest and sweetest people i've ever met and im so grateful for you. we met when times were really tough and I really appreciate you constantly checking up on me. not just me, but it's also so lovely that even though you yourself have had a hard time recently you always make sure to check up on everyone else and make sure everyone's doing okay. you're genuinely such a good person and im so so happy we became friends. i'm proud to be your little sister. i hope you heal from all the pain you've ever faced and i know you will because you're so strong. take care of yourself and please please feel free to message me if you ever need anything. happy birthday again, i love you! 🤍❤️‍🩹 - Selly",
  "Hey Richie, Happiest birthday My Shylaaa! I wish You all the happiness, success & prosperity in your life. I hope every single day of your life will be as joyful as you made mine. Sending you a warm hug. I hope every single sorrow & trouble leave you forever. Hey You made it feel like home. Thank you for coming into my life everything you have done for me I can't explain in words what it means to me. I feel safe around you. So thank you you stay just the way you are 'cause you are Per- fect. My mental asylum roommate,  little Mr. Obsessed over my Zayn Bhaiyyuuu from calling me Eleanor & I started fighting with you to us like camila & fighting over her still she's MINE stay away from her. Because of u I met Apoorva so thank you so much from sending unreleased songs to actually Becoming someone I'll never ghost ever. I promise for life. Have a great day & year ahead. & never forget to smile like louis dadda said I remember you laughing So let's just laugh again.  - Raniya Firdous ",
  "Happy Birthday, Riche! Wishing you a day filled with love, laughter, and all the happiness you bring to those around you. May this year be full of exciting adventures, beautiful moments, and dreams coming true. Keep shining and being your wonderful self! Have an amazing day! xx Lipi",
  "Happy birthday Richie!!!!!!! You are one of the best people in my life. You are amazing person and I care so much about you. You look like a prince. You are a great listener and advice giver and I’m extremely thankful to know you. I hope you have an amazing birthday. Please stay always healthy and stay who you are.You bring me so much joy, laughter and love in to my life and into the world.  I hope this year brings you all the happiness you deserve and more. Here’s to another year of unforgettable memories. Your kindness, loyalty, and infectious energy make the world a better place. With lots of love.Virginia <3",
  "Happiest birthday, Richie bhai! May this birthday bring lots of joy, hope, and prosperity into your life. Thank you for always giving me a listening ear when I needed someone to talk to, and for being with me through tough times. I would like to thank you from the bottom of my heart for always creating a safe space for all of us in the group chat. You are a kind and beautiful soul! Hoping to stay connected always, lots of love to you bhai. Sherly X",
  "Happy birthday dadujiiii. This is apoo, i just want to say that your one of the best and genuine people i met through internet. You are just amazing, the work your doing with creating the safe space of everyone is just admirable!! And it's very rare these days to find people as beautiful as you are both from inside and outside!! The way u welcome people with open heart is just wow!!! U deserve all the happiness in the world. May god bless u with all the things u desire for and may u meet zayn and u guyssss write together and may u be the most amazing rapper and writer. Again don't forget that u are wonderful and amazing and beautiful inside and outside.Happy birthday once again!!!! Party hard and enjoy!!!!  - Apoorva ",
  "HAPPY BIRTHDAY TO YOUUU HAPPY BIRTHDAY TO YOUUU HAPPY BIRTHDAY DEAR RICHIE RICH HAPPY BIRTHDAY TO YOUUU MAY GOD BLESS YOU MAY GOD BLESS YOU HAPPY BIRTHDAY DEAR RICHIE RICH HAPPY BIRTHDAY TO YOUUUU   happy birthday dearrrr richieee 😭🩷 I don't know where to start but thank you for always being one of the bestest online friend I've ever had. You've always been there for me and that means the world to me....i have never seen or met someone sooo fun and sooooo caring and sooooo amazing as you ..I am really really really glad to have such a beautiful soul in my life and I will always pray for your growth and your wellness....you're an angel in human form and I hope all of your wishes come true and you have a really really awesome and full of joy life ahead....you deserve all of the happiness in the world and you've always been so kind to the world that the world will give it back to you ..and remember that I Will always Be here for you no matter what....thank you for being the brother I've never had and thank you for always having my back....being the support that I never had....your amaZayn brilLiam extraordiHarry fabuLouis phenomeNiall you're absolutely beautiful inside out and I am really really thankful for everything you've done and I am always going to be here for you through everything. You can count on me . Happy birthday to the bestest human 🩷 love you soooo muchhhhh and I am very very proud of you 🩷🩷 all the love 🩷🩷 - Shravani ",
  "Soo today's the day ur born my lordd what can I say to a wordsmith but I'll try promise u won't laugh tho. So richie rich what is there to say about u I haven't known u that long but the moment I started texting in thr group you've been nothing short of kind and the person who always tries to get everyone involved thank you for that really you're one of the kindest and sweetest person ik (bear w me I say that about everyone so don't let ur ego go through yeah) Whenever anyone's having a bad day or js need to vent ur the guy my guy. Never stop being kind Never stop being so mastikhor Never stop caring Never stop being human Never stop being icon cause ur the moment🗣🗣😍 Never stop being you Never stop being richie <33 HAPPY BIRTHDAY AND LOVE YA LOADDSSSS HOPE YOU HAVE FUN!!!🥰🥰🎀🥳  - Shruti ",
  "Happppppiiieee birthdayyyyy Jaani Dushman🎊🎀 There's not a lot to say here but if there's one thing I can say then it would be for you to find your happiness now, prioritise yourself. May this birthday bring in all happiness that you crave and deserve :) Abb ship pe jaake don't forget thik hai😂 - Kashish",
  "Vassssup youuu gettting olldddddd🎀😋😂😂 Well i hopeeee ki the planss you madeee for you lifee those you talk about and those you dont i hopeee saaaree completee ho jaaye and do nott everrrrr changeee you the mossttt amazinggg persooonnnn sooo fookin dont stopppp bakchodi karnaaa🎀😋😋‼️- Abhishek",
];

let currentIndex = 0;

// Function to update message boxes
function updateMessages() {
  document.getElementById("message1").innerText =
    messages[currentIndex % messages.length];
  document.getElementById("message2").innerText =
    messages[(currentIndex + 1) % messages.length];
  document.getElementById("message3").innerText =
    messages[(currentIndex + 2) % messages.length];

  currentIndex += 3;
}

// Start updating messages every 5 seconds
updateMessages();
setInterval(updateMessages, 15000);
